    INSERT INTO films (name, type, released_date, description) VALUES
    ('Star Wars: Episode IV - A New Hope', 'SCI_FY', '1977-05-25', 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire''s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.'),
    ('Star Wars: Episode V - The Empire Strikes Back', 'SCI_FY', '1980-05-21', 'After the Rebels are overpowered by the Empire on their newly established base, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.'),
    ('Star Wars: Episode VI - Return of the Jedi', 'SCI_FY', '1983-05-25', 'After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor''s trap.'),
    ('Star Wars: Episode I - The Phantom Menace', 'SCI_FY', '1999-05-19', 'Two Jedi escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to reclaim their old glory.'),
    ('Star Wars: Episode II - Attack of the Clones', 'SCI_FY', '2002-05-16', 'Ten years after initially meeting, Anakin Skywalker shares a forbidden romance with Padmé Amidala, while Obi-Wan Kenobi investigates an assassination attempt on the senator and discovers a secret clone army crafted for the Jedi.'),
    ('Star Wars: Episode III - Revenge of the Sith', 'SCI_FY', '2005-05-19', 'Three years into the Clone Wars, the Jedi rescue Palpatine from Count Dooku. As Obi-Wan pursues a new threat, Anakin acts as a double agent between the Jedi Council and Palpatine and is lured into a sinister plan to rule the galaxy.'),
    ('Star Wars: Episode VII - The Force Awakens', 'SCI_FY', '2015-12-18', 'As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.'),
    ('Star Wars: Episode VIII - The Last Jedi', 'SCI_FY', '2017-12-15', 'The Resistance is in shambles after a devastating attack, and the New Republic struggles to defend against the First Order. Rey trains with Luke Skywalker to master the Force and understand her connection to Kylo Ren.'),
    ('Star Wars: Episode IX - The Rise of Skywalker', 'SCI_FY', '2019-12-20', 'The surviving members of the Resistance face the First Order once again, and the legendary conflict between the Jedi and the Sith reaches its peak, bringing the Skywalker saga to a close.');


